language: ruby

bundler_args: "--binstubs --standalone --without documentation --path ../bundle"
script: "bundle exec rake test"
rvm:
  - 2.3.8
  - 2.4.5
  - 2.5.3
  - 2.6.1
  - jruby-head
  - truffleruby
matrix:
  allow_failures:
    - rvm: jruby-head
    - rvm: truffleruby
notifications:
  email: false
