language: ruby
sudo: false
cache:
  - bundler
before_install: gem update bundler
bundler_args: "--binstubs --standalone --without documentation"
script: "bundle exec rake test"
rvm:
  - 2.2.0
  - 2.3.3
  - 2.4.0
notifications:
  email: false
